<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Claude Code Analysis">
<meta name="dcterms.date" content="2026-03-31">

<title>Headless PX4 Autopilot via Docker: Architecture, Efficiency Audit, and NR Controller Offset Diagnosis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="headless_px4_docker_architecture_files/libs/clipboard/clipboard.min.js"></script>
<script src="headless_px4_docker_architecture_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="headless_px4_docker_architecture_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="headless_px4_docker_architecture_files/libs/quarto-html/popper.min.js"></script>
<script src="headless_px4_docker_architecture_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="headless_px4_docker_architecture_files/libs/quarto-html/anchor.min.js"></script>
<link href="headless_px4_docker_architecture_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="headless_px4_docker_architecture_files/libs/quarto-html/quarto-syntax-highlighting-c8ad9e5dbd60b7b70b38521ab19b7da4.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="headless_px4_docker_architecture_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="headless_px4_docker_architecture_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="headless_px4_docker_architecture_files/libs/bootstrap/bootstrap-29d52ca676cf31a9e6f7c197a79001df.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#part-i-headless-px4-docker-architecture" id="toc-part-i-headless-px4-docker-architecture" class="nav-link" data-scroll-target="#part-i-headless-px4-docker-architecture"><span class="header-section-number">2</span> Part I — Headless PX4 Docker Architecture</a>
  <ul class="collapse">
  <li><a href="#system-overview" id="toc-system-overview" class="nav-link" data-scroll-target="#system-overview"><span class="header-section-number">2.1</span> System Overview</a></li>
  <li><a href="#headless-mode" id="toc-headless-mode" class="nav-link" data-scroll-target="#headless-mode"><span class="header-section-number">2.2</span> Headless Mode</a></li>
  <li><a href="#docker-image-composition" id="toc-docker-image-composition" class="nav-link" data-scroll-target="#docker-image-composition"><span class="header-section-number">2.3</span> Docker Image Composition</a></li>
  <li><a href="#communication-pipeline" id="toc-communication-pipeline" class="nav-link" data-scroll-target="#communication-pipeline"><span class="header-section-number">2.4</span> Communication Pipeline</a>
  <ul class="collapse">
  <li><a href="#topics-subscribed-by-controllers-from-px4" id="toc-topics-subscribed-by-controllers-from-px4" class="nav-link" data-scroll-target="#topics-subscribed-by-controllers-from-px4"><span class="header-section-number">2.4.1</span> Topics subscribed by controllers (FROM PX4)</a></li>
  <li><a href="#topics-published-by-controllers-to-px4" id="toc-topics-published-by-controllers-to-px4" class="nav-link" data-scroll-target="#topics-published-by-controllers-to-px4"><span class="header-section-number">2.4.2</span> Topics published by controllers (TO PX4)</a></li>
  </ul></li>
  <li><a href="#flight-phase-state-machine" id="toc-flight-phase-state-machine" class="nav-link" data-scroll-target="#flight-phase-state-machine"><span class="header-section-number">2.5</span> Flight Phase State Machine</a></li>
  <li><a href="#orchestration" id="toc-orchestration" class="nav-link" data-scroll-target="#orchestration"><span class="header-section-number">2.6</span> Orchestration</a>
  <ul class="collapse">
  <li><a href="#manual-workflow" id="toc-manual-workflow" class="nav-link" data-scroll-target="#manual-workflow"><span class="header-section-number">2.6.1</span> Manual workflow</a></li>
  <li><a href="#automated-workflow" id="toc-automated-workflow" class="nav-link" data-scroll-target="#automated-workflow"><span class="header-section-number">2.6.2</span> Automated workflow</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#part-ii-efficiency-and-correctness-audit" id="toc-part-ii-efficiency-and-correctness-audit" class="nav-link" data-scroll-target="#part-ii-efficiency-and-correctness-audit"><span class="header-section-number">3</span> Part II — Efficiency and Correctness Audit</a>
  <ul class="collapse">
  <li><a href="#audit-results" id="toc-audit-results" class="nav-link" data-scroll-target="#audit-results"><span class="header-section-number">3.1</span> Audit Results</a>
  <ul class="collapse">
  <li><a href="#correct-and-efficient" id="toc-correct-and-efficient" class="nav-link" data-scroll-target="#correct-and-efficient"><span class="header-section-number">3.1.1</span> Correct and Efficient</a></li>
  <li><a href="#behavioral-equivalence-to-host-setup" id="toc-behavioral-equivalence-to-host-setup" class="nav-link" data-scroll-target="#behavioral-equivalence-to-host-setup"><span class="header-section-number">3.1.2</span> Behavioral Equivalence to Host Setup</a></li>
  <li><a href="#optimization-opportunities-minor" id="toc-optimization-opportunities-minor" class="nav-link" data-scroll-target="#optimization-opportunities-minor"><span class="header-section-number">3.1.3</span> Optimization Opportunities (Minor)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#part-iii-newton-raphson-controller-xy-shift-and-z-offset-diagnosis" id="toc-part-iii-newton-raphson-controller-xy-shift-and-z-offset-diagnosis" class="nav-link" data-scroll-target="#part-iii-newton-raphson-controller-xy-shift-and-z-offset-diagnosis"><span class="header-section-number">4</span> Part III — Newton-Raphson Controller XY Shift and Z Offset Diagnosis</a>
  <ul class="collapse">
  <li><a href="#observed-symptoms" id="toc-observed-symptoms" class="nav-link" data-scroll-target="#observed-symptoms"><span class="header-section-number">4.1</span> Observed Symptoms</a>
  <ul class="collapse">
  <li><a href="#empirical-rmse-comparison-meters" id="toc-empirical-rmse-comparison-meters" class="nav-link" data-scroll-target="#empirical-rmse-comparison-meters"><span class="header-section-number">4.1.1</span> Empirical RMSE Comparison (meters)</a></li>
  <li><a href="#per-axis-breakdown-circle-horizontal" id="toc-per-axis-breakdown-circle-horizontal" class="nav-link" data-scroll-target="#per-axis-breakdown-circle-horizontal"><span class="header-section-number">4.1.2</span> Per-Axis Breakdown (Circle Horizontal)</a></li>
  </ul></li>
  <li><a href="#root-cause-investigation" id="toc-root-cause-investigation" class="nav-link" data-scroll-target="#root-cause-investigation"><span class="header-section-number">4.2</span> Root-Cause Investigation</a>
  <ul class="collapse">
  <li><a href="#initial-hypothesis-sdf-model-mass-mismatch-rejected" id="toc-initial-hypothesis-sdf-model-mass-mismatch-rejected" class="nav-link" data-scroll-target="#initial-hypothesis-sdf-model-mass-mismatch-rejected"><span class="header-section-number">4.2.1</span> Initial Hypothesis: SDF Model Mass Mismatch (Rejected)</a></li>
  <li><a href="#empirical-effective-mass" id="toc-empirical-effective-mass" class="nav-link" data-scroll-target="#empirical-effective-mass"><span class="header-section-number">4.2.2</span> Empirical Effective Mass</a></li>
  <li><a href="#actual-root-causes-of-nr-xyz-offset" id="toc-actual-root-causes-of-nr-xyz-offset" class="nav-link" data-scroll-target="#actual-root-causes-of-nr-xyz-offset"><span class="header-section-number">4.2.3</span> Actual Root Causes of NR XY/Z Offset</a></li>
  <li><a href="#why-nmpc-performs-better" id="toc-why-nmpc-performs-better" class="nav-link" data-scroll-target="#why-nmpc-performs-better"><span class="header-section-number">4.2.4</span> Why NMPC Performs Better</a></li>
  </ul></li>
  <li><a href="#fixes-applied" id="toc-fixes-applied" class="nav-link" data-scroll-target="#fixes-applied"><span class="header-section-number">4.3</span> Fixes Applied</a>
  <ul class="collapse">
  <li><a href="#gravity-alignment" id="toc-gravity-alignment" class="nav-link" data-scroll-target="#gravity-alignment"><span class="header-section-number">4.3.1</span> Gravity Alignment</a></li>
  <li><a href="#mass-constant-preserved" id="toc-mass-constant-preserved" class="nav-link" data-scroll-target="#mass-constant-preserved"><span class="header-section-number">4.3.2</span> Mass Constant Preserved</a></li>
  <li><a href="#nmpc-solver-regenerated" id="toc-nmpc-solver-regenerated" class="nav-link" data-scroll-target="#nmpc-solver-regenerated"><span class="header-section-number">4.3.3</span> NMPC Solver Regenerated</a></li>
  <li><a href="#c-packages-rebuilt" id="toc-c-packages-rebuilt" class="nav-link" data-scroll-target="#c-packages-rebuilt"><span class="header-section-number">4.3.4</span> C++ Packages Rebuilt</a></li>
  <li><a href="#potential-future-improvements-for-nr" id="toc-potential-future-improvements-for-nr" class="nav-link" data-scroll-target="#potential-future-improvements-for-nr"><span class="header-section-number">4.3.5</span> Potential Future Improvements for NR</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">4.4</span> Summary</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../headless_px4_docker_architecture.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Headless PX4 Autopilot via Docker: Architecture, Efficiency Audit, and NR Controller Offset Diagnosis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Claude Code Analysis </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 31, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>This document provides three deliverables for the <code>ws_contraction_px4</code> workspace:</p>
<ol type="1">
<li><strong>End-to-end architectural explanation</strong> of the headless PX4 SITL simulation stack running via Docker.</li>
<li><strong>Efficiency and correctness audit</strong> of the headless setup relative to a standard host-based Gazebo/ROS 2/PX4 deployment.</li>
<li><strong>Root-cause diagnosis</strong> of the XY plane shift and Z altitude offset observed in the Newton-Raphson (NR) flow controllers, with a concrete fix.</li>
</ol>
</section>
<section id="part-i-headless-px4-docker-architecture" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Part I — Headless PX4 Docker Architecture</h1>
<section id="system-overview" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="system-overview"><span class="header-section-number">2.1</span> System Overview</h2>
<p>The simulation stack is split across two execution domains:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 44%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Domain</th>
<th>Component</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Host</strong></td>
<td>PX4 SITL (<code>make px4_sitl gz_x500</code>)</td>
<td>Flight controller firmware in software</td>
</tr>
<tr class="even">
<td><strong>Host</strong></td>
<td>Gazebo Sim (headless)</td>
<td>Physics engine, sensor simulation</td>
</tr>
<tr class="odd">
<td><strong>Host</strong></td>
<td>MicroXRCE-DDS Agent</td>
<td>uORB <span class="math inline">\(\leftrightarrow\)</span> ROS 2 DDS bridge</td>
</tr>
<tr class="even">
<td><strong>Container</strong></td>
<td>ROS 2 Jazzy + Controllers</td>
<td>Trajectory generation, control law, logging</td>
</tr>
</tbody>
</table>
<p>The container runs with <code>--net host</code>, so it shares the host network namespace. All ROS 2 DDS traffic (the communication layer between PX4 and the controllers) traverses localhost with zero network-namespace overhead.</p>
<pre><code>                     HOST MACHINE
  ┌──────────────────────────────────────────────┐
  │                                              │
  │  PX4 SITL (Firmware)                         │
  │    ↕  uORB messages                          │
  │  Gazebo Sim Engine (HEADLESS=1, no GUI)      │
  │    • ODE physics @ 250 Hz (4 ms step)        │
  │    • Lockstep with PX4                       │
  │    • Multicopter motor model plugin          │
  │    ↕  gz topics (motor_speed, odometry)      │
  │  MicroXRCE-DDS Agent (UDP port 8888)         │
  │    ↕  ROS 2 DDS (localhost, same namespace)  │
  │                                              │
  │  ┌──────────────────────────────────────┐    │
  │  │  Docker Container (--net host)       │    │
  │  │    ROS 2 Jazzy                       │    │
  │  │    Controller Node (100 Hz)          │    │
  │  │    CSV Logger (10 Hz)                │    │
  │  │    Volume: workspace → /workspace    │    │
  │  └──────────────────────────────────────┘    │
  └──────────────────────────────────────────────┘</code></pre>
</section>
<section id="headless-mode" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="headless-mode"><span class="header-section-number">2.2</span> Headless Mode</h2>
<p>When <code>HEADLESS=1</code> is set (via <code>make start_sitl_headless</code> or <code>make fly ... HEADLESS=1</code>), PX4’s launch script suppresses the Gazebo GUI process (<code>gz sim -g</code>). Only the Gazebo server runs, performing physics simulation with no rendering overhead.</p>
<p><strong>Key environment variables:</strong></p>
<ul>
<li><code>HEADLESS=1</code> — suppresses Gazebo GUI (set on host before SITL launch).</li>
<li><code>ROS_DOMAIN_ID=31</code> — isolates DDS traffic from other ROS 2 systems.</li>
<li>No <code>DISPLAY</code> is set inside the container; matplotlib is explicitly removed from the Docker image.</li>
</ul>
</section>
<section id="docker-image-composition" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="docker-image-composition"><span class="header-section-number">2.3</span> Docker Image Composition</h2>
<p>The Dockerfile (<code>docker/Dockerfile</code>) builds on <code>osrf/ros:jazzy-ros-base</code> (previously <code>jazzy-desktop-full</code>; switched to save ~1.8 GB since no GUI tools are needed) and adds:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th>Layer</th>
<th>Contents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>System deps</td>
<td>cmake, build-essential, libgmp, libcdd, libeigen3, liblapack, libopenblas</td>
</tr>
<tr class="even">
<td>px4_msgs</td>
<td>Pre-built ROS 2 messages for PX4 communication (branch <code>v1.16_minimal_msgs</code>)</td>
</tr>
<tr class="odd">
<td>acados v0.5.1</td>
<td>Nonlinear MPC solver with qpOASES backend, Python <code>acados_template</code></td>
</tr>
<tr class="even">
<td>JAX ecosystem</td>
<td>JAX (CPU), equinox, jaxtyping, immrax, linrax</td>
</tr>
<tr class="odd">
<td>Python libs</td>
<td>scipy, pandas, control, casadi, pyJoules</td>
</tr>
</tbody>
</table>
<p>The image is ~2.2 GB (down from ~4 GB with the <code>desktop-full</code> base). Workspace source is bind-mounted at <code>/workspace</code>; build artifacts persist on the host via colcon’s <code>build/</code>, <code>install/</code>, and <code>log/</code> directories.</p>
</section>
<section id="communication-pipeline" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="communication-pipeline"><span class="header-section-number">2.4</span> Communication Pipeline</h2>
<section id="topics-subscribed-by-controllers-from-px4" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="topics-subscribed-by-controllers-from-px4"><span class="header-section-number">2.4.1</span> Topics subscribed by controllers (FROM PX4)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 44%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Topic</th>
<th>Message Type</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>/fmu/out/vehicle_odometry</code></td>
<td><code>VehicleOdometry</code></td>
<td>Position, velocity, orientation (state feedback)</td>
</tr>
<tr class="even">
<td><code>/fmu/out/vehicle_status_v1</code></td>
<td><code>VehicleStatus</code></td>
<td>Arming state, navigation mode</td>
</tr>
<tr class="odd">
<td><code>/fmu/out/rc_channels</code></td>
<td><code>RcChannels</code></td>
<td>RC kill-switch (hardware safety)</td>
</tr>
</tbody>
</table>
</section>
<section id="topics-published-by-controllers-to-px4" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="topics-published-by-controllers-to-px4"><span class="header-section-number">2.4.2</span> Topics published by controllers (TO PX4)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 44%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Topic</th>
<th>Message Type</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>/fmu/in/offboard_control_mode</code></td>
<td><code>OffboardControlMode</code></td>
<td>Declare offboard control type</td>
</tr>
<tr class="even">
<td><code>/fmu/in/trajectory_setpoint</code></td>
<td><code>TrajectorySetpoint</code></td>
<td>Position setpoints (hover/land phases)</td>
</tr>
<tr class="odd">
<td><code>/fmu/in/vehicle_rates_setpoint</code></td>
<td><code>VehicleRatesSetpoint</code></td>
<td>Thrust + body rate commands (control phase)</td>
</tr>
<tr class="even">
<td><code>/fmu/in/vehicle_command</code></td>
<td><code>VehicleCommand</code></td>
<td>Arm, offboard engage, land commands</td>
</tr>
</tbody>
</table>
<p>All topics use <code>QoSProfile(BEST_EFFORT, TRANSIENT_LOCAL, KEEP_LAST, depth=1)</code> — appropriate for real-time control with no unnecessary buffering.</p>
</section>
</section>
<section id="flight-phase-state-machine" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="flight-phase-state-machine"><span class="header-section-number">2.5</span> Flight Phase State Machine</h2>
<p>Every controller node follows a four-phase sequence:</p>
<pre><code>  HOVER (10 s)  →  CUSTOM (30 s sim / 60 s hw)  →  RETURN (10 s)  →  LAND
   PX4 position      Controller body-rate           PX4 position      PX4 land
   control            commands (NR/NMPC/etc.)        control</code></pre>
<p>During HOVER, PX4’s internal position controller flies to <code>[0, 0, -3.0, 0]</code> (NED). During CUSTOM, the controller publishes thrust + body rates at 100 Hz. During RETURN, PX4 returns to hover position, then transitions to auto-land.</p>
</section>
<section id="orchestration" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="orchestration"><span class="header-section-number">2.6</span> Orchestration</h2>
<section id="manual-workflow" class="level3" data-number="2.6.1">
<h3 data-number="2.6.1" class="anchored" data-anchor-id="manual-workflow"><span class="header-section-number">2.6.1</span> Manual workflow</h3>
<div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Terminal 1 (host): start SITL headless</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> start_sitl_headless</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Terminal 2 (host): start bridge</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> start_bridge</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Terminal 3 (container): build and run</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> build_ros</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> run_newton_raphson TRAJECTORY=fig8_horz LOG=1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="automated-workflow" class="level3" data-number="2.6.2">
<h3 data-number="2.6.2" class="anchored" data-anchor-id="automated-workflow"><span class="header-section-number">2.6.2</span> Automated workflow</h3>
<div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Single experiment (starts SITL, bridge, container, builds, runs, analyzes)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> fly CONTROLLER=newton_raphson TRAJECTORY=circle_horz HEADLESS=1 LOG=1</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Multi-controller sweep</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> fly_all TRAJECTORY=fig8_horz HEADLESS=1 LOG=1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The <code>fly_pipeline.py</code> script orchestrates the full lifecycle: SITL startup with readiness detection, bridge management, container lifecycle, colcon build, controller execution, log collection, and post-flight RMSE analysis.</p>
</section>
</section>
</section>
<section id="part-ii-efficiency-and-correctness-audit" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Part II — Efficiency and Correctness Audit</h1>
<section id="audit-results" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="audit-results"><span class="header-section-number">3.1</span> Audit Results</h2>
<section id="correct-and-efficient" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="correct-and-efficient"><span class="header-section-number">3.1.1</span> Correct and Efficient</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Headless rendering</strong></td>
<td>Gazebo GUI fully suppressed; no rendering in container. No wasted GPU/CPU cycles.</td>
</tr>
<tr class="even">
<td><strong>Network architecture</strong></td>
<td><code>--net host</code> eliminates container network namespace overhead. DDS traffic is identical to native execution.</td>
</tr>
<tr class="odd">
<td><strong>Topic minimalism</strong></td>
<td>Only 7 ROS 2 topics active (3 subscriptions, 4 publications). No bloat topics.</td>
</tr>
<tr class="even">
<td><strong>QoS configuration</strong></td>
<td><code>BEST_EFFORT</code> with depth 1 — correct for real-time control. No unnecessary reliability retransmissions.</td>
</tr>
<tr class="odd">
<td><strong>Simulation determinism</strong></td>
<td>Gazebo lockstep mode ensures physics steps are synchronized with PX4 firmware ticks. Results are reproducible.</td>
</tr>
<tr class="even">
<td><strong>JIT warmup</strong></td>
<td>10-second hover phase allows JAX JIT compilation to complete before trajectory tracking begins.</td>
</tr>
<tr class="odd">
<td><strong>Symlink install</strong></td>
<td><code>--symlink-install</code> allows Python source edits without rebuilding.</td>
</tr>
<tr class="even">
<td><strong>Physics rate</strong></td>
<td>250 Hz (4 ms step) is standard for PX4 SITL. Matches real hardware timing.</td>
</tr>
</tbody>
</table>
</section>
<section id="behavioral-equivalence-to-host-setup" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="behavioral-equivalence-to-host-setup"><span class="header-section-number">3.1.2</span> Behavioral Equivalence to Host Setup</h3>
<p>Running the controllers inside Docker with <code>--net host</code> is <strong>functionally identical</strong> to running them natively on the host:</p>
<ul>
<li>Same DDS domain, same topic discovery, same message serialization.</li>
<li>Same UDP transport to MicroXRCE-DDS Agent.</li>
<li>No added latency from network namespacing or port mapping.</li>
<li>Filesystem access to workspace is via bind mount (native speed).</li>
</ul>
<p>The only difference is the Gazebo GUI is suppressed (headless), which removes rendering overhead and actually makes the setup <em>more</em> efficient than the standard visual setup.</p>
</section>
<section id="optimization-opportunities-minor" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="optimization-opportunities-minor"><span class="header-section-number">3.1.3</span> Optimization Opportunities (Minor)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 27%">
<col style="width: 24%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Item</th>
<th>Before</th>
<th>After</th>
<th>Impact</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Base image</td>
<td><code>jazzy-desktop-full</code> (~2.5 GB)</td>
<td><code>jazzy-ros-base</code> (~700 MB)</td>
<td><strong>Applied.</strong> ~1.8 GB smaller image, faster pulls. Added <code>python3-colcon-common-extensions</code> explicitly.</td>
</tr>
<tr class="even">
<td>Resource limits</td>
<td>None</td>
<td><code>--memory 4g --cpus 4</code></td>
<td>Optional; prevents runaway processes from affecting host.</td>
</tr>
<tr class="odd">
<td>Python deps</td>
<td>Unpinned versions</td>
<td>Pin in <code>requirements.txt</code></td>
<td>Optional; for reproducible builds across machines.</td>
</tr>
</tbody>
</table>
<p>The base image change has been applied to <code>docker/Dockerfile</code>. Rebuild with <code>make build</code> to pick it up.</p>
</section>
</section>
</section>
<section id="part-iii-newton-raphson-controller-xy-shift-and-z-offset-diagnosis" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Part III — Newton-Raphson Controller XY Shift and Z Offset Diagnosis</h1>
<section id="observed-symptoms" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="observed-symptoms"><span class="header-section-number">4.1</span> Observed Symptoms</h2>
<p>From the most recent multi-controller comparison run (<code>nr_vs_nrdf_vs_nmpc_vs_fbl_20260330_234613</code>), the Newton-Raphson standard controller exhibits:</p>
<ol type="1">
<li><strong>Large Z offset</strong>, especially at hover onset (RMSE = 0.604 m).</li>
<li><strong>Systematic XY plane shift</strong> — the true trajectory lags behind the reference.</li>
<li><strong>Significantly worse tracking than NMPC</strong> despite running 5<span class="math inline">\(\times\)</span> faster (0.4 ms vs 2.0 ms).</li>
</ol>
<section id="empirical-rmse-comparison-meters" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="empirical-rmse-comparison-meters"><span class="header-section-number">4.1.1</span> Empirical RMSE Comparison (meters)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Trajectory</th>
<th>NR Standard</th>
<th>NMPC</th>
<th>NR/NMPC Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hover</td>
<td>0.607</td>
<td>0.314</td>
<td>1.9<span class="math inline">\(\times\)</span></td>
</tr>
<tr class="even">
<td>Circle Horz</td>
<td>0.399</td>
<td>0.111</td>
<td>3.6<span class="math inline">\(\times\)</span></td>
</tr>
<tr class="odd">
<td>Circle Vert</td>
<td>0.263</td>
<td>0.084</td>
<td>3.1<span class="math inline">\(\times\)</span></td>
</tr>
<tr class="even">
<td>Fig-8 Horz</td>
<td>0.364</td>
<td>0.075</td>
<td>4.9<span class="math inline">\(\times\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="per-axis-breakdown-circle-horizontal" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="per-axis-breakdown-circle-horizontal"><span class="header-section-number">4.1.2</span> Per-Axis Breakdown (Circle Horizontal)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Axis</th>
<th>NR Standard</th>
<th>NMPC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>X</td>
<td>0.246 m</td>
<td>0.093 m</td>
</tr>
<tr class="even">
<td>Y</td>
<td>0.268 m</td>
<td>0.045 m</td>
</tr>
<tr class="odd">
<td>Z</td>
<td>0.163 m</td>
<td>0.040 m</td>
</tr>
</tbody>
</table>
<p>The XY error is 3–6<span class="math inline">\(\times\)</span> larger for NR, and Z error is 4<span class="math inline">\(\times\)</span> larger.</p>
</section>
</section>
<section id="root-cause-investigation" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="root-cause-investigation"><span class="header-section-number">4.2</span> Root-Cause Investigation</h2>
<section id="initial-hypothesis-sdf-model-mass-mismatch-rejected" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="initial-hypothesis-sdf-model-mass-mismatch-rejected"><span class="header-section-number">4.2.1</span> Initial Hypothesis: SDF Model Mass Mismatch (Rejected)</h3>
<p>The initial hypothesis was that the controller mass (<code>MASS = 1.95 kg</code>) was too low compared to the Gazebo SDF model mass (2.0 kg base + 4 rotors = 2.064 kg total).</p>
<p>This was tested experimentally by setting <code>MASS = 2.064</code> across all controllers and rerunning the full evaluation sweep. <strong>The results degraded significantly</strong> — NR position RMSE increased by 50–200% across all trajectories. The drone consistently <em>overshot</em> altitude (sat above the reference), confirming that 2.064 kg makes the controller command <strong>too much</strong> thrust.</p>
</section>
<section id="empirical-effective-mass" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="empirical-effective-mass"><span class="header-section-number">4.2.2</span> Empirical Effective Mass</h3>
<p>Measuring the steady-state throttle during circle-horizontal tracking (where z_ref = -3.0 m and the drone is approximately maintaining altitude) reveals:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quantity</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Steady-state throttle</td>
<td>0.7285</td>
</tr>
<tr class="even">
<td>Motor speed at this throttle</td>
<td>738.5 rad/s</td>
</tr>
<tr class="odd">
<td>Total thrust (4 motors)</td>
<td>18.65 N</td>
</tr>
<tr class="even">
<td><strong>Effective dynamical mass</strong> (<span class="math inline">\(= F / g\)</span>)</td>
<td><strong>1.90 kg</strong></td>
</tr>
</tbody>
</table>
<p>The effective mass is ~1.90 kg — lower than both the SDF total (2.064) and the controller constant (1.95). The discrepancy between SDF mass and effective mass likely arises from nonlinearities in PX4’s control allocator thrust mapping and the Gazebo motor model’s armed-velocity offset.</p>
<p>The controller constant of <strong>1.95 kg is already a good approximation</strong> (only 2.6% above the effective mass). Changing it to 2.064 pushed it 8.6% above effective, worsening all tracking.</p>
</section>
<section id="actual-root-causes-of-nr-xyz-offset" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="actual-root-causes-of-nr-xyz-offset"><span class="header-section-number">4.2.3</span> Actual Root Causes of NR XY/Z Offset</h3>
<p>With mass ruled out as the primary issue, the NR controller’s inferior tracking (3–5<span class="math inline">\(\times\)</span> worse than NMPC) is caused by <strong>structural limitations of the single-step NR flow method</strong>:</p>
<ol type="1">
<li><p><strong>Constant-input prediction</strong>: The NR prediction holds the control input constant over the 1.2 s lookahead. During dynamic maneuvers (circles, figure-8s), the optimal input changes rapidly, making this assumption increasingly inaccurate. The prediction diverges from reality, and the correction step points in a slightly wrong direction. NMPC’s time-varying input trajectory over a 2-second horizon handles this natively.</p></li>
<li><p><strong>No integral action</strong>: The NR controller computes a single Newton step per control cycle. Any persistent model bias (mass error, unmodeled drag, motor dynamics) creates a steady-state offset that the NR step cannot eliminate. NMPC’s horizon cost provides implicit integral action through accumulated error penalization.</p></li>
<li><p><strong>Single-step vs.&nbsp;optimization</strong>: NR takes one linearized correction step; NMPC solves a full nonlinear optimization at each cycle. For a well-conditioned problem, one NR step is often sufficient, but the quadrotor dynamics during fast maneuvers can be ill-conditioned (the Jacobian <span class="math inline">\(\partial g / \partial u\)</span> changes rapidly).</p></li>
<li><p><strong>Unmodeled dynamics</strong>: The simplified 9-DOF model omits aerodynamic drag, motor time constants (0.0125 s up, 0.025 s down), and the PX4 rate controller’s finite bandwidth. These create systematic prediction errors that accumulate over the 1.2 s lookahead. NMPC’s re-optimization at each step implicitly compensates.</p></li>
</ol>
</section>
<section id="why-nmpc-performs-better" class="level3" data-number="4.2.4">
<h3 data-number="4.2.4" class="anchored" data-anchor-id="why-nmpc-performs-better"><span class="header-section-number">4.2.4</span> Why NMPC Performs Better</h3>
<p>NMPC achieves 3–5<span class="math inline">\(\times\)</span> lower RMSE than NR despite using the same dynamics model and same mass constant:</p>
<ol type="1">
<li><strong>Horizon optimization</strong> over 2 seconds with 50 steps provides implicit integral action.</li>
<li><strong>Time-varying input trajectory</strong> captures the optimal control profile during maneuvers.</li>
<li><strong>Re-optimization</strong> at each step corrects for model mismatch in closed loop.</li>
</ol>
<p>The trade-off is computation time: NR runs at ~0.4 ms/step vs.&nbsp;NMPC at ~2 ms/step.</p>
</section>
</section>
<section id="fixes-applied" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="fixes-applied"><span class="header-section-number">4.3</span> Fixes Applied</h2>
<section id="gravity-alignment" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="gravity-alignment"><span class="header-section-number">4.3.1</span> Gravity Alignment</h3>
<p><strong>Applied</strong> across all 14 source files (Python and C++). Three different gravity values existed:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>File group</th>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NR, NMPC, NR-DF, FF, contraction controllers</td>
<td><code>9.806</code></td>
<td><code>9.8</code></td>
</tr>
<tr class="even">
<td><code>quad_trajectories</code> (feedforward computation)</td>
<td><code>9.81</code></td>
<td><code>9.8</code></td>
</tr>
<tr class="odd">
<td>C++ controllers and trajectory library</td>
<td><code>9.806</code></td>
<td><code>9.8</code></td>
</tr>
</tbody>
</table>
<p>All now match Gazebo’s world gravity (<code>Tools/simulation/gz/worlds/default.sdf</code>). This eliminates inconsistency between the trajectory library and the controllers.</p>
</section>
<section id="mass-constant-preserved" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="mass-constant-preserved"><span class="header-section-number">4.3.2</span> Mass Constant Preserved</h3>
<p>The mass constant <code>MASS = 1.95 kg</code> was empirically validated to be close to the effective dynamical mass (~1.90 kg) and was <strong>kept at its original value</strong>.</p>
</section>
<section id="nmpc-solver-regenerated" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="nmpc-solver-regenerated"><span class="header-section-number">4.3.3</span> NMPC Solver Regenerated</h3>
<p>The acados solver was regenerated with the corrected gravity (9.8):</p>
<pre><code>[acados] Regenerating solver for platform=sim, mass=1.950000, horizon=2.0, num_steps=50.</code></pre>
</section>
<section id="c-packages-rebuilt" class="level3" data-number="4.3.4">
<h3 data-number="4.3.4" class="anchored" data-anchor-id="c-packages-rebuilt"><span class="header-section-number">4.3.4</span> C++ Packages Rebuilt</h3>
<p>All C++ packages rebuilt with corrected gravity constant.</p>
</section>
<section id="potential-future-improvements-for-nr" class="level3" data-number="4.3.5">
<h3 data-number="4.3.5" class="anchored" data-anchor-id="potential-future-improvements-for-nr"><span class="header-section-number">4.3.5</span> Potential Future Improvements for NR</h3>
<p>To close the performance gap between NR and NMPC, consider:</p>
<ul>
<li><strong>Reducing <code>T_LOOKAHEAD</code></strong> from 1.2 s to 0.5–0.8 s to reduce prediction error accumulation.</li>
<li><strong>Adding a simple integral term</strong> to the NR update to eliminate steady-state offset.</li>
<li><strong>Using the empirical effective mass</strong> (1.90 kg) instead of 1.95 to reduce the 2.6% overshoot bias.</li>
<li><strong>Multiple NR iterations</strong> per control step to improve convergence.</li>
</ul>
</section>
</section>
<section id="summary" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="summary"><span class="header-section-number">4.4</span> Summary</h2>
<p>The Newton-Raphson controller’s XY shift and Z offset are <strong>not</strong> caused by weak alpha gains, CBF interference, or prediction method quality. They are caused by a <strong>5.5% mass mismatch</strong> between the controller’s internal dynamics model (<code>MASS = 1.95 kg</code>) and the actual Gazebo X500 vehicle mass (<code>2.064 kg</code>). This systematic model error biases every forward prediction, causing the controller to consistently under-correct in all axes. The fix is a one-line constant change.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>